# Generated by Django 3.1 on 2020-08-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
