# Generated by Django 3.1 on 2020-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Department',
            field=models.CharField(choices=[('ece', 'ECE'), ('cse', 'CSE'), ('it', 'IT'), ('eee', 'EEE'), ('mech', 'MECH'), ('civil', 'CIVIL')], max_length=20),
        ),
    ]
