# Generated by Django 3.1 on 2020-08-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
