# Generated by Django 3.1 on 2020-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_faculty_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
