# Generated by Django 3.1 on 2020-08-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0004_auto_20200811_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='faculty',
            name='Mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
